/******************************************************************************
 *
 * Project       : Operational Applications UI Foundation
 *
 * Description   : The model-view-viewmodel library of generic UI components
 *
 * Author        : Gennady Pospelov (IO)
 *
 * Copyright (c) : 2010-2020 ITER Organization,
 *                 CS 90 046
 *                 13067 St. Paul-lez-Durance Cedex
 *                 France
 *
 * This file is part of ITER CODAC software.
 * For the terms and conditions of redistribution or use of this software
 * refer to the file ITER-LICENSE.TXT located in the top level directory
 * of the distribution package.
 *****************************************************************************/

#ifndef FOLDERBASEDTEST_H
#define FOLDERBASEDTEST_H

#include <gtest/gtest.h>

#include <string>

//! Convenience class which creates a directory on disk for test content.

class FolderBasedTest : public ::testing::Test
{
public:
  explicit FolderBasedTest(std::string folder_name);
  ~FolderBasedTest() override;

  std::string GetTestFolderName() const;

  std::string GetTestDirectory() const;

  std::string GetFilePath(const std::string& file_name) const;

  std::string CreateEmptyDir(const std::string& subdir) const;

protected:
  std::string m_folder_name;  //! The name of the folder for files generated by this test.
};

#endif  //  FOLDERBASEDTEST_H
