// ************************************************************************** //
//
//  Operational Applications UI Foundation
//
// ************************************************************************** //

#include "test_utils.h"

#include "testconfig.h"  // this file is auto generated by the build system in build directory

#include <filesystem>
#include <string>
#include <fstream>
#include <sstream>

namespace
{
const std::string header{R"RAW(<?xml version="1.0" encoding="UTF-8"?>
<root>)RAW"};

const std::string footer{R"RAW(</root>
)RAW"};

}  // namespace

namespace TestUtils
{
std::string GetTestOutputDir()
{
  return TestConfig::TestOutputDir();  // defined in auto-generated testconfig.h
}

std::string CreateXMLDocumentString(const std::string& body)
{
  return header + body + footer;
}

std::string GetTextFileContent(const std::string &file_name)
{
  std::ifstream in(file_name);
  std::stringstream sstr;
  while(in >> sstr.rdbuf());
  return sstr.str();
}

}  // namespace TestUtils
