/******************************************************************************
 *
 * Project       : Operational Applications UI Foundation
 *
 * Description   : The model-view-viewmodel library of generic UI components
 *
 * Author        : Gennady Pospelov (IO)
 *
 * Copyright (c) : 2010-2020 ITER Organization,
 *                 CS 90 046
 *                 13067 St. Paul-lez-Durance Cedex
 *                 France
 *
 * This file is part of ITER CODAC software.
 * For the terms and conditions of redistribution or use of this software
 * refer to the file ITER-LICENSE.TXT located in the top level directory
 * of the distribution package.
 *****************************************************************************/

#include "test_utils.h"

#include "testconfig.h"  // this file is auto generated by the build system in build directory

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace
{
const std::string header{R"RAW(<?xml version="1.0" encoding="UTF-8"?>
<root>)RAW"};

const std::string footer{R"RAW(</root>
)RAW"};

}  // namespace

namespace TestUtils
{
std::string GetTestOutputDir()
{
  return TestConfig::TestOutputDir();  // defined in auto-generated testconfig.h
}

std::string CreateXMLDocumentString(const std::string &body)
{
  return header + body + footer;
}

std::string GetTextFileContent(const std::string &file_name)
{
  std::ifstream in(file_name);
  std::stringstream sstr;
  while (in >> sstr.rdbuf())
  {
  }
  return sstr.str();
}

void CreateTextFile(const std::string &file_name, const std::string &content)
{
  std::ofstream file_out(file_name);
  file_out.write(content.c_str(), content.size());
}

}  // namespace TestUtils
