/******************************************************************************
 *
 * Project       : Operational Applications UI Foundation
 *
 * Description   : The model-view-viewmodel library of generic UI components
 *
 * Author        : Gennady Pospelov (IO)
 *
 * Copyright (c) : 2010-2024 ITER Organization,
 *                 CS 90 046
 *                 13067 St. Paul-lez-Durance Cedex
 *                 France
 *
 * This file is part of ITER CODAC software.
 * For the terms and conditions of redistribution or use of this software
 * refer to the file ITER-LICENSE.TXT located in the top level directory
 * of the distribution package.
 *****************************************************************************/

#include "folder_test.h"

#include "testconfig.h"  // this file is auto generated by the build system in build directory

namespace mvvm::test
{

FolderTest::FolderTest(std::string test_home_dirname)
    : FolderOutputBasedTest(GetTestSuiteOutputDir(), std::move(test_home_dirname))
{
}

std::string GetTestSuiteOutputDir()
{
  return TestConfig::TestOutputDir();  // defined in auto-generated testconfig.h
}

std::string GetProjectSourceDir()
{
  return TestConfig::ProjectSourceDir();  // defined in auto-generated testconfig.h
}

}  // namespace mvvm::test
