/******************************************************************************
 *
 * Project       : Operational Applications UI Foundation
 *
 * Description   : The model-view-viewmodel library of generic UI components
 *
 * Author        : Gennady Pospelov (IO)
 *
 * Copyright (c) : 2010-2023 ITER Organization,
 *                 CS 90 046
 *                 13067 St. Paul-lez-Durance Cedex
 *                 France
 *
 * This file is part of ITER CODAC software.
 * For the terms and conditions of redistribution or use of this software
 * refer to the file ITER-LICENSE.TXT located in the top level directory
 * of the distribution package.
 *****************************************************************************/

#ifndef LIBTEST_UTILS_TESTUTILS_FOLDER_BASED_TEST_H_
#define LIBTEST_UTILS_TESTUTILS_FOLDER_BASED_TEST_H_

#include <gtest/gtest.h>

#include <string>

namespace mvvm::test
{

//! Convenience class which creates a directory on disk for test content.

class FolderBasedTest : public ::testing::Test
{
public:
  explicit FolderBasedTest(std::string test_home_dirname);
  ~FolderBasedTest() override;

  std::string GetTestHomeDirName() const;

  std::string GetTestHomeDir() const;

  std::string GetFilePath(const std::string& file_name) const;

  std::string CreateEmptyDir(const std::string& subdir) const;

private:
  std::string m_test_home_dirname;  //! The name of the folder for files generated by this test.
};

}  // namespace testutils

#endif  // LIBTEST_UTILS_TESTUTILS_FOLDER_BASED_TEST_H_
