/******************************************************************************
 *
 * Project       : Operational Applications UI Foundation
 *
 * Description   : The model-view-viewmodel library of generic UI components
 *
 * Author        : Gennady Pospelov (IO)
 *
 * Copyright (c) : 2010-2020 ITER Organization,
 *                 CS 90 046
 *                 13067 St. Paul-lez-Durance Cedex
 *                 France
 *
 * This file is part of ITER CODAC software.
 * For the terms and conditions of redistribution or use of this software
 * refer to the file ITER-LICENSE.TXT located in the top level directory
 * of the distribution package.
 *****************************************************************************/

#ifndef MVVM_SIGNALS_ITEMLISTENERBASE_H
#define MVVM_SIGNALS_ITEMLISTENERBASE_H

#include "mvvm/model_export.h"
#include "mvvm/signals/callback_types.h"
#include "mvvm/signals/signalslot.h"

#include <memory>

namespace mvvm
{

//! Provides sets of methods to subscribe to various signals generated by SessionItem.
//! Used to implement user actions on item change.

class MVVM_MODEL_EXPORT ItemListenerBase
{
public:
  explicit ItemListenerBase();
  virtual ~ItemListenerBase();

  ItemListenerBase& operator=(const ItemListenerBase& other) = delete;
  ItemListenerBase(const ItemListenerBase& other) = delete;

  void SetItem(SessionItem* item);

  void SetOnDataChange(Callbacks::item_int_t f);

protected:
  SessionItem* GetCurrentItem() const;

  virtual void subscribe() {}    //! For necessary manipulations on new item.
  virtual void unsubscribe() {}  //! For necessary manipulations on unsubscription.

private:
  struct ItemListenerBaseImpl;
  std::unique_ptr<ItemListenerBaseImpl> p_impl;
};

}  // namespace mvvm

#endif  // MVVM_SIGNALS_ITEMLISTENERBASE_H
