/******************************************************************************
 *
 * Project       : Operational Applications UI Foundation
 *
 * Description   : The model-view-viewmodel library of generic UI components
 *
 * Author        : Gennady Pospelov (IO)
 *
 * Copyright (c) : 2010-2022 ITER Organization,
 *                 CS 90 046
 *                 13067 St. Paul-lez-Durance Cedex
 *                 France
 *
 * This file is part of ITER CODAC software.
 * For the terms and conditions of redistribution or use of this software
 * refer to the file ITER-LICENSE.TXT located in the top level directory
 * of the distribution package.
 *****************************************************************************/

#ifndef MVVM_SIGNALS_ITEMLISTENER_H
#define MVVM_SIGNALS_ITEMLISTENER_H

#include <mvvm/signals/item_listener_base.h>

namespace mvvm
{

class SessionItem;

//! Base class to subscribe to signals generated by SessionItem of certain type.

template <typename T>
class ItemListener : public ItemListenerBase
{
public:
  T* GetItem() const { return static_cast<T*>(GetCurrentItem()); }
};

}  // namespace mvvm

#endif  // MVVM_SIGNALS_ITEMLISTENER_H
