/******************************************************************************
 *
 * Project       : Operational Applications UI Foundation
 *
 * Description   : The model-view-viewmodel library of generic UI components
 *
 * Author        : Gennady Pospelov (IO)
 *
 * Copyright (c) : 2010-2020 ITER Organization,
 *                 CS 90 046
 *                 13067 St. Paul-lez-Durance Cedex
 *                 France
 *
 * This file is part of ITER CODAC software.
 * For the terms and conditions of redistribution or use of this software
 * refer to the file ITER-LICENSE.TXT located in the top level directory
 * of the distribution package.
 *****************************************************************************/

#ifndef MVVM_SIGNALS_MODELLISTENERBASE_H
#define MVVM_SIGNALS_MODELLISTENERBASE_H

#include "mvvm/model_export.h"
#include "mvvm/signals/callback_types.h"
#include "mvvm/signals/signalslot.h"

#include <memory>

namespace mvvm
{

class ApplicationModel;

//! Provides sets of methods to subscribe to various signals generated by SessionModel.

class MVVM_MODEL_EXPORT ModelListenerBase
{
public:
  explicit ModelListenerBase(ApplicationModel* model);
  virtual ~ModelListenerBase();

  //! Sets callback to be notified when the item is about to be inserted. The callback will be
  //! called with (SessionItem* parent, tag_index), where 'tag_index' denotes child position.
  Connection SetOnAboutToInsertItem(const Callbacks::item_tagindex_t& f);

  //! Sets callback to be notified on item insert. The callback will be called with
  //! (SessionItem* parent, tag_index), where 'tag_index' denotes child position after insert.
  Connection SetOnItemInserted(const Callbacks::item_tagindex_t& f);

  //! Sets callback to be notified when the item is about to be removed. The callback will be
  //! called with (SessionItem* parent, tag_index), where 'tag_index' denotes child position being
  //! removed.
  Connection SetOnAboutToRemoveItem(const Callbacks::item_tagindex_t& f);

  //! Sets callback to be notified on item remove. The callback will be called with
  //! (SessionItem* parent, tag_index), where 'tag_index' denotes child position before the removal.
  Connection SetOnItemRemoved(const Callbacks::item_tagindex_t& f);

  //! Sets callback to be notified on item's data change. The callback will be called
  //! with (SessionItem*, data_role).
  Connection SetOnDataChanged(const Callbacks::item_int_t& f);

  //! Sets the callback to be notified just before the reset of the root item.
  Connection SetOnModelAboutToBeReset(const Callbacks::model_t& f);

  //! Sets the callback to be notified right after the root item recreation.
  Connection SetOnModelReset(const Callbacks::model_t& f);

  //! Sets the callback for notifications just before model destruction.
  Connection SetOnModelAboutToBeDestroyed(const Callbacks::model_t& f);

private:
  struct ModelListenerBaseImpl;
  std::unique_ptr<ModelListenerBaseImpl> p_impl;
};

}  // namespace mvvm

#endif  // MVVM_SIGNALS_MODELLISTENERBASE_H
